site_name: ACCESS Output Data Specifications
theme:
  name: readthedocs
  highlightjs: true
plugins:
  - search
  - with-pdf

nav:
  - Specification: specification.md
  - Mapping: mapping.md

extra_css:
  - https://cdn.datatables.net/2.3.4/css/dataTables.dataTables.min.css
  - css/table.css

extra_javascript:
  - https://cdn.datatables.net/2.3.4/js/dataTables.min.js
  - javascripts/site.js

plugins:
  - with-pdf:
      author: ACCESS-NRI
      cover_subtitle: ""
      copyright: "{release_version}"
      toc_level: 3
      exclude_pages:
        - 'mapping/'
