name: Build README

on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  setup:
    name: Setup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v5
        # The following is needed to allow add-and-commit below to work
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Setup python
        uses: actions/setup-python@v6

      - name: Install dependancies
        run: python -m pip install -r requirements.txt

      - name: Update README.md
        run: python scripts/update_readme.py

      - name: Cat README.md in lieu of commit
        run: cat README.md

      - name: Commit updated README.md
        uses: EndBug/add-and-commit@v9
        permissions:
          contents: write
        with:
          add: README.md
