name: JSON Schema CI

on: [pull_request, push, workflow_dispatch]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5.0.0
      - uses: sourcemeta/jsonschema@v11.8.3
      - uses: pre-commit/action@v3.0.1

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install the Sourcemeta JSON Schema CLI
        uses: sourcemeta/jsonschema@v11.8.3

      - name: Check schemas against their metaschemas
        run: jsonschema metaschema --verbose schema/

      - name: Check schemas are formatted
        run: jsonschema fmt --check --verbose schema/

      - name: Lint schemas
        run: jsonschema lint --verbose schema/

      - name: Run test suite
        run: jsonschema test --verbose tests/ --resolve schema
